#!/usr/bin/env ruby
folder = "#{Dir.home}/.commshots/"
Dir.mkdir(folder) unless File.directory?(folder)
file="#{folder}#{Time.now.to_i}.jpg"
puts "Taking capture into #{file}!"
system "imagesnap -q -w 2 #{file}"
exit 0
